version: '3.8'

services:
  cantinho-algarvio:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - cantinho-network

networks:
  cantinho-network:
    driver: bridge