   // Importar a biblioteca dotenv
   import { config } from 'dotenv';
   config(); // Carregar as variáveis de ambiente do arquivo .env

   import { createClient } from '@supabase/supabase-js';
   import type { Database } from './types';

   // Usar variáveis de ambiente
   const SUPABASE_URL = process.env.SUPABASE_URL || '';
   const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || '';

   export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
     db: {
       schema: 'public',
     },
     global: {
       headers: {
         'x-my-custom-header': 'my-app-name',
       },
     },
   });

   declare module '@supabase/supabase-js' {
     interface SupabaseClient {
       from<T>(table: 'event_requests'): EventRequest[];
       from<T>(table: 'event_invoices'): EventInvoice[];
     }
   }

   type EventRequest = { /* define properties */ };
   type EventInvoice = { /* define properties */ };

// This file is automatically generated. Do not edit it directly.
/*import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bueecgmyuqbfgyftlqcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1ZWVjZ215dXFiZmd5ZnRscWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4NDQxNDEsImV4cCI6MjA0OTQyMDE0MX0.ahRq6O0-I1blWu25cXHljQhGScX6Stu7NIeT5NI62WA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public',
  },
  // Estendendo a definição do banco de dados para incluir novas tabelas
  global: {
    headers: {
      'x-my-custom-header': 'my-app-name',
    },
  },
});

// Estendendo manualmente o tipo para event_requests e event_invoices
// Esta é uma solução temporária até que os tipos sejam atualizados
declare module '@supabase/supabase-js' {
  interface SupabaseClient {
    from<T>(table: 'event_requests'): any;
    from<T>(table: 'event_invoices'): any;
  }
}*/
