// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bueecgmyuqbfgyftlqcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1ZWVjZ215dXFiZmd5ZnRscWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4NDQxNDEsImV4cCI6MjA0OTQyMDE0MX0.ahRq6O0-I1blWu25cXHljQhGScX6Stu7NIeT5NI62WA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);